language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env:
      - TOX_ENV=py27
    - python: 3.4
      env:
      - TOX_ENV=py34
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36

install:
    - pip install tox-travis coveralls

script:
    - tox

after_success:
    - coveralls
