apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: $SERVICE_RUN_LABEL
  name: job-db-migrate-$TAG
  namespace: default
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: job-db-migrate
      labels:
        run: $SERVICE_RUN_LABEL
    spec:
      containers:
      - name: $CONTAINER_NAME
        image: $IMAGE_NAME:$TAG
        imagePullPolicy: Always
        command: ["python", "manage.py", "migrate"]
        env:
        - name: ENV
          value: $ENV
        - name: DB_NAME
          value: $DB_NAME
        - name: DB_USER
          value: $DB_USER
        - name: DB_PASS
          value: $DB_PASS
        - name: DB_HOST
          value: $DB_HOST
        - name: DB_PORT
          value: "$DB_PORT"
      restartPolicy: Never
