apiVersion: batch/v1
kind: Job
metadata:
  labels:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
  name: job-db-migrate-$TAG
  namespace: default
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: job-db-migrate
      labels:
        env: $ENV
        project: $LABEL_PROJECT
        service: $LABEL_SERVICE
    spec:
      containers:
      - name: $CONTAINER_NAME
        image: $IMAGE_NAME:$TAG
        imagePullPolicy: Always
        command: ["python", "manage.py", "migrate"]
        env:
        - name: ENV
          value: $ENV
      restartPolicy: Never
