apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
  name: $DEPLOYMENT_NAME-$COLOR
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      env: $ENV
      project: $LABEL_PROJECT
      service: $LABEL_SERVICE
  template:
    metadata:
      labels:
        env: $ENV
        project: $LABEL_PROJECT
        service: $LABEL_SERVICE
        type: deployment
        color: $COLOR
    spec:
      containers:
      - command: ["gunicorn", "django_app.wsgi", "--name", "todoapp", "-b", ":$CONTAINER_PORT"]
        env:
        - name: ENV
          value: $ENV
        - name: COLOR
          value: $COLOR
        image: $IMAGE_NAME:$TAG
        name: $CONTAINER_NAME
        readinessProbe:
          httpGet:
            path: /ready
            port: container-port
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /live
            port: container-port
          initialDelaySeconds: 30
        ports:
        - name: container-port
          containerPort: $CONTAINER_PORT
          protocol: TCP
