apiVersion: v1
kind: Service
metadata:
  labels:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
  name: $SERVICE_NAME
  namespace: default
spec:
  type: NodePort
  ports:
  - port: $SERVICE_PORT
    targetPort: $CONTAINER_PORT
    protocol: TCP
    name: http
  selector:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
    color: $COLOR
    type: pod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $INGRESS_NAME
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
spec:
  rules:
    - host: $INGRESS_SUBDOMAIN.$DOMAIN_NAME
      http:
        paths:
          - path: /
            backend:
              serviceName: $SERVICE_NAME
              servicePort: $SERVICE_PORT
