apiVersion: v1
kind: Service
metadata:
  labels:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
  name: $SMOKE_SERVICE_NAME
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: $SERVICE_PORT
    targetPort: $CONTAINER_PORT
    protocol: TCP
    name: http
  selector:
    env: $ENV
    project: $LABEL_PROJECT
    service: $LABEL_SERVICE
    type: deployment
    color: $COLOR
