apiVersion: v1
kind: Service
metadata:
  labels:
    run: $SERVICE_RUN_LABEL
  name: $SMOKE_SERVICE_NAME
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: $SERVICE_PORT
    targetPort: $CONTAINER_PORT
  selector:
    run: $SERVICE_RUN_LABEL
    type: deployment
    color: $COLOR
  type: LoadBalancer
